#!/usr/bin/env ruby

require 'optparse'
require 'cubist'

app = Cubist::App.new

options = {}
OptionParser.new do |opt|
  opt.on('--dir DIR') { |o| options[:dir] = o }
  opt.on('--first_name FIRSTNAME') { |o| options[:first_name] = o }
  opt.on('--last_name LASTNAME') { |o| options[:last_name] = o }
  opt.on('--make_perspective PERSPECTIVE') { |o| options[:make_perspective] = o }
end.parse!

if options.key?(:dir)
  app.set_project_root(options[:dir])
else
  STDERR.puts "please set the dir with --dir"
  exit 1
end

if options.key?(:make_perspective)
  app.make_perspective(options[:make_perspective])
end
