#!/usr/bin/env ruby

require 'optparse'
require 'cubist'

app = Cubist::App.new

options = {}
OptionParser.new do |opt|
  opt.on('--dir DIR') { |o| options[:dir] = o }
  opt.on('--make_angle ANGLE') { |o| options[:make_angle] = o }
  opt.on('--get_angles') { |o| options[:get_angles] = true }
  opt.on('--get_related_files FILES') { |o| options[:get_related_files] = o }
end.parse!

if options.key?(:dir)
  app.set_project_root(options[:dir])
else
  STDERR.puts "please set the dir with --dir"
  exit 1
end

if options.key?(:get_angles)
  puts app.get_angles()
  exit 0
end

if options.key?(:make_angle)
  app.make_angle(options[:make_angle])
  exit 0
end

if options.key?(:get_related_files)
  files = options[:get_related_files].split(/,/)
  app.get_related_files(files)
  exit 0
end
